language: python

matrix:
  include:

    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial

    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial

install:
  - pip install .

script:
  - python -c "import gqcnn"

notifications:
  email: false