version: 2.1 # use CircleCI 2.1

## Setup python executor ##
executors:
  python:
    docker:
      - image: circleci/python:3.5
    shell: /bin/bash
    working_directory: ~/project
    steps:

## Ci jobs ##
jobs: # A basic unit of work in a run

  ## Python 3.5 build_test ##
  python3_5:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout
      - run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py35venv

      # upgrade pip and install dependencies
      - run: |

            # Before install
            sudo apt-get update
            sudo apt-get install -y\
              python-opengl \
              vim

            # Install dependencies
            . py35venv/bin/activate
            pip install --upgrade pip
            pip install . # Install panda_autograsp requirements

      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}
          paths:
            - "py35venv"

      # Perform package build successful test
      - run: |
          . py35venv/bin/activate
          python3 tests/test_gqcnn.py

  ## Python 3.6 build_test ##
  python3_6:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout
      - run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py36venv

      # upgrade pip and install dependencies
      - run: |

            # Before install
            sudo apt-get update
            sudo apt-get install -y\
              python-opengl \
              vim

            # Install dependencies
            . py36venv/bin/activate
            pip install --upgrade pip
            pip install . # Install panda_autograsp requirements

      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}
          paths:
            - "py36venv"

      # Perform package build successful test
      - run: |
          . py36venv/bin/activate
          python3 tests/test_gqcnn.py

  ## Python 3.7 build_test ##
  python3_7:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout
      - run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py37venv

      # upgrade pip and install dependencies
      - run: |

            # Before install
            sudo apt-get update
            sudo apt-get install -y\
              python-opengl \
              vim

            # Install dependencies
            . py37venv/bin/activate
            pip install --upgrade pip
            pip install . # Install panda_autograsp requirements

      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/dev_requirements.txt" }}
          paths:
            - "py37venv"

      # Perform package build successful test
      - run: |
          . py37venv/bin/activate
          python3 tests/test_gqcnn.py

## Ci workflow ##
workflows:
  version: 2.1
  build_test:
    jobs:
      #- python3_5
      #- python3_6
      - python3_7