version: 2.1 # use CircleCI 2.1

## Setup python executor ##
executors:
  python:
    docker:
      - image: circleci/python:3.5
    shell: /bin/bash
    working_directory: ~/project

## Ci jobs ##
jobs: # A basic unit of work in a run

  ## Python 3.5 build_test ##
  python3_5:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - run: echo "python3.5 test"
      - run: pwd
      - run: ls ../

  ## Python 3.5 build_test ##
  python3_6:
    docker:
      - image: circleci/python:3.6
    executor: python
    steps: # steps that comprise the `python3.5` job
      - run: echo "python3.6 test"
      - run: pwd
      - run: ls ../

  ## Python 3.7 build_test ##
  python3_7:
    docker:
      - image: circleci/python:3.7
    executor: python
    steps: # steps that comprise the `python3.5` job
      - run: echo "python3.7 test"
      - run: pwd
      - run: ls ../../


workflows:
  version: 2.1
  build_test:
    jobs:
      - python3_5
      - python3_6
      - python3_7