version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run

  ## Python 3.6 build_test ##
  python3.6:

    # directory where steps are run
    working_directory: ~/panda_autograsp-circleci
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6
    steps: # steps that comprise the `build_test` job
      - run: pwd