version: 2.1 # use CircleCI 2.1

## Setup python executor ##
executors:
  python:
    docker:
      - image: circleci/python:3.5
    shell: /bin/bash
    working_directory: ~/project

## Ci jobs ##
jobs: # A basic unit of work in a run

  ## Python 3.5 build_test ##
  python3_5:
    executor: python
    steps: # steps that comprise the `python3.5` job
      
      # restore virtual enviroment dependencies from chache #
      - restore_cache: 
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - checkout
      - run: pwd
      - run: ls
      - run: | # Create virtual env
            python3 -m venv py35venv
            . py35venv/bin/activate
            pip install .
      - save_cache: # Save virtual enviroment dependencies in chache
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py35venv"

      # Perform import test
      - run: |
        . py35venv/bin/activate
        import gqcnn

  ## Python 3.5 build_test ##
  python3_6:
    executor: python
    steps: # steps that comprise the `python3.5` job
      
      # restore virtual enviroment dependencies from chache #
      - restore_cache: 
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - checkout
      - run: pwd
      - run: ls
      - run: | # Create virtual env
            python3 -m venv py35venv
            . py36venv/bin/activate
            pip install .
      - save_cache: # Save virtual enviroment dependencies in chache
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py36venv"

      # Perform import test
      - run: |
        . py36venv/bin/activate
        import gqcnn

  ## Python 3.5 build_test ##
  python3_7:
    executor: python
    steps: # steps that comprise the `python3.5` job
      
      # restore virtual enviroment dependencies from chache #
      - restore_cache: 
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - checkout
      - run: pwd
      - run: ls
      - run: | # Create virtual env
            python3 -m venv py35venv
            . py37venv/bin/activate
            pip install .
      - save_cache: # Save virtual enviroment dependencies in chache
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py37venv"

      # Perform import test
      - run: |
        . py37venv/bin/activate
        import gqcnn

workflows:
  version: 2.1
  build_test:
    jobs:
      - python3_5
      - python3_6
      - python3_7