version: 2.1 # use CircleCI 2.1

## Setup python executor ##
executors:
  python:
    docker:
      - image: circleci/python:3.5
    shell: /bin/bash
    working_directory: ~/project
    steps:

## Ci jobs ##
jobs: # A basic unit of work in a run

  ## Python 3.5 build_test ##
  python3_5:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: pwd
      - run: ls
      - run: | # Create virtual env, upgrade pip and get dependencies
            sudo apt -y -q install curl
            curl -O https://bootstrap.pypa.io/get-pip.py && \
              python3 get-pip.py && \
              rm get-pip.py
            python3 -m venv py35venv
            . py35venv/bin/activate
            pip install --user .
      - save_cache: # Save virtual environment dependencies in cache
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py35venv"

      # Perform package build successful test
      - run: |
          . py35venv/bin/activate
          python3 tests/test_import.py

  ## Python 3.5 build_test ##
  python3_6:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: pwd
      - run: ls
      - run: | # Create virtual env, upgrade pip and get dependencies
            sudo apt -y -q install curl
            curl -O https://bootstrap.pypa.io/get-pip.py && \
              python3 get-pip.py && \
              rm get-pip.py
            python3 -m venv py36venv
            . py35venv/bin/activate
            pip install --user .
      - save_cache: # Save virtual environment dependencies in cache
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py36venv"

      # Perform package build successful test
      - run: |
          . py36venv/bin/activate
          python3 tests/test_import.py

  ## Python 3.5 build_test ##
  python3_7:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: pwd
      - run: ls
      - run: | # Create virtual env, upgrade pip and get dependencies
            sudo apt -y -q install curl
            curl -O https://bootstrap.pypa.io/get-pip.py && \
              python3 get-pip.py && \
              rm get-pip.py
            python3 -m venv py35venv
            . py37venv/bin/activate
            pip install --user .
      - save_cache: # Save virtual environment dependencies in cache
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py37venv"

      # Perform package build successful test
      - run: |
          . py37venv/bin/activate
          python3 tests/test_import.py

## Ci workflow ##
workflows:
  version: 2.1
  build_test:
    jobs:
      - python3_5
      - python3_6
      - python3_7