version: 2.1 # use CircleCI 2.1

## Setup python executor ##
executors:
  python:
    docker:
      - image: circleci/python:3.5
    shell: /bin/bash
    working_directory: ~/project
    steps:

## Ci jobs ##
jobs: # A basic unit of work in a run

  ## Python 3.5 build_test ##
  python3_5:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py35venv
            . py35venv/bin/activate

      # upgrade pip and install dependencies
      - run: |
            . py35venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 setup.py install # Install panda_autograsp requirements
            python3 -m pip install gqcnn/. # Install gqcnn requirements (Needed in free circle-ci version)

      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy35-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py35venv"

      # Perform package build successful test
      - run: |
          . py35venv/bin/activate
          python3 tests/test_gqcnn.py

  ## Python 3.6 build_test ##
  python3_6:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py36venv
            . py36venv/bin/activate

      # upgrade pip and install dependencies
      - run: |
            . py36venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 setup.py install # Install panda_autograsp requirements
            python3 -m pip install gqcnn/. # Install gqcnn requirements (Needed in free circle-ci version)


      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy36-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py36venv"

      # Perform package build successful test
      - run: |
          . py37venv/bin/activate
          python3 tests/test_gqcnn.py

  ## Python 3.5 build_test ##
  python3_7:
    executor: python
    steps: # steps that comprise the `python3.5` job
      - checkout
      - run: git submodule sync --recursive gqcnn
      - run: git submodule update --recursive --init gqcnn

      # restore virtual environment dependencies from cache #
      - restore_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}

      # install dependencies #
      - run: | # Create virtual env
            python3 -m venv py37venv
            . py37venv/bin/activate

      # upgrade pip and install dependencies
      - run: |

            # Before install
            sudo apt-get update
            sudo apt-get install -y python-opengl

            # Install dependencies
            . py37venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 setup.py install # Install panda_autograsp requirements
            pip install gqcnn/. # Install gqcnn requirements (Needed in free circle-ci version)

      # Save virtual environment dependencies in cache
      - save_cache:
          key: depspy37-{{ .Branch }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - "py37venv"

      # Perform package build successful test
      - run: |
          . py37venv/bin/activate
          python -c "import gqcnn"

## Ci workflow ##
workflows:
  version: 2.1
  build_test:
    jobs:
      #- python3_5
      #- python3_6
      - python3_7